version: '2'

networks:
  artist-den:
    external: false


services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    networks:
      - artist-den
    ports:
      - '8000:80'
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      - artist-den
    environment:
      - MYSQL_ROOT_PASSWORD=289252
      - MYSQL_DATABASE=artist-den
    volumes:
      - ./mysql:/var/lib/mysql